"""update user model

Revision ID: b0342c3ea6e0
Revises: aeb5ef59f530
Create Date: 2025-05-12 04:09:37.982459+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0342c3ea6e0'
down_revision: Union[str, None] = 'aeb5ef59f530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('company_website', sa.String(), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(), nullable=True))
    op.add_column('users', sa.Column('state', sa.String(), nullable=True))
    op.add_column('users', sa.Column('timezone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('language', sa.String(), nullable=True))
    op.create_index('ix_users_country', 'users', ['country'], unique=False)
    op.create_index('ix_users_state', 'users', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_state', table_name='users')
    op.drop_index('ix_users_country', table_name='users')
    op.drop_column('users', 'language')
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'state')
    op.drop_column('users', 'country')
    op.drop_column('users', 'company_website')
    op.drop_column('users', 'company_name')
    # ### end Alembic commands ###
