"""added opened at and relation with document and template

Revision ID: af60ac2ba1cb
Revises: 15a47af1dc0c
Create Date: 2025-06-05 05:53:38.505736+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af60ac2ba1cb'
down_revision: Union[str, None] = '15a47af1dc0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_conversations', sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('template_id', sa.UUID(), nullable=True))
    op.create_index('ix_documents_template_id', 'documents', ['template_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'templates', ['template_id'], ['id'])
    op.add_column('workspaces', sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'opened_at')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index('ix_documents_template_id', table_name='documents')
    op.drop_column('documents', 'template_id')
    op.drop_column('documents', 'opened_at')
    op.drop_column('chat_conversations', 'opened_at')
    # ### end Alembic commands ###
