"""removed descope user id

Revision ID: b6c0d12a9913
Revises: db890e06de36
Create Date: 2025-05-02 06:41:00.103953+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6c0d12a9913'
down_revision: Union[str, None] = 'db890e06de36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_descope_user_id', table_name='users')
    op.drop_column('users', 'descope_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('descope_user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_users_descope_user_id', 'users', ['descope_user_id'], unique=False)
    # ### end Alembic commands ###
