"""add icon and feedback

Revision ID: aeb5ef59f530
Revises: b6c0d12a9913
Create Date: 2025-05-06 13:26:14.727605+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeb5ef59f530'
down_revision: Union[str, None] = 'b6c0d12a9913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_conversations', sa.Column('icon', sa.String(), nullable=True))
    op.add_column('chat_messages', sa.Column('is_liked', sa.Boolean(), nullable=True))
    op.add_column('chat_messages', sa.Column('feedback_types', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('chat_messages', sa.Column('feedback_comment', sa.Text(), nullable=True))
    op.add_column('chat_messages', sa.Column('feedback_timestamp', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'feedback_timestamp')
    op.drop_column('chat_messages', 'feedback_comment')
    op.drop_column('chat_messages', 'feedback_types')
    op.drop_column('chat_messages', 'is_liked')
    op.drop_column('chat_conversations', 'icon')
    # ### end Alembic commands ###
